import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header/header'
import StoreProvider from '@/services/storeProvider'
import UserUpdateComponent from '@/components/userUpdate/userUpdate'
import React from 'react'

export const metadata: Metadata = {
  title: 'КБ ГЛОБАЛ',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
    <body className='body'>
    <StoreProvider>
      <UserUpdateComponent>
        <Header/>
        {children}
      </UserUpdateComponent>
    </StoreProvider>
    </body>
    </html>
  )
}
