import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import StoreProvider from "@/services/StoreProvider";
import UserUpdateComponent from "@/components/UserUpdate/UserUpdate";
import React from "react";

export const metadata: Metadata = {
  title: "КБ ГЛОБАЛ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="body">
        <StoreProvider>
          <UserUpdateComponent>
            <Header />
            {children}
          </UserUpdateComponent>
        </StoreProvider>
      </body>
    </html>
  );
}
