export const data = [
  {
    _id: "kratornaya-bulka-n-200i",
    name: "Краторная булка N-200i",
    type: "bun",
    proteins: 80,
    fat: 24,
    carbohydrates: 53,
    calories: 420,
    price: 1255,
    images: {
      image: "https://code.s3.yandex.net/react/code/bun-02.png",
      image_mobile: "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
      video: "https://www.youtube.com/embed/ENBv2i88g6Y?si=x-kLHo5Waezag_aj",
    },
    __v: 0,
  },
  {
    _id: "govyazhiy-meteorit-otbivnaya",
    name: "Говяжий метеорит (отбивная)",
    type: "main",
    proteins: 800,
    fat: 800,
    carbohydrates: 300,
    calories: 2674,
    price: 3000,
    images: {
      image: "https://code.s3.yandex.net/react/code/meat-04.png",
      image_mobile: "https://code.s3.yandex.net/react/code/meat-04-mobile.png",
    },
    __v: 0,
  },
  {
    _id: "biokotleta-iz-marsianskoy-magnolii",
    name: "Биокотлета из марсианской Магнолии",
    type: "main",
    proteins: 420,
    fat: 142,
    carbohydrates: 242,
    calories: 4242,
    price: 424,
    images: {
      image: "https://code.s3.yandex.net/react/code/meat-01.png",
      image_mobile: "https://code.s3.yandex.net/react/code/meat-01-mobile.png",
      video: "https://www.youtube.com/embed/vjVkXlxsO8Q?si=fOLlY2GPg8hsrAb2",
    },
    __v: 0,
  },
  {
    _id: "sous-spicy-x",
    name: "Соус Spicy-X",
    type: "sauce",
    proteins: 30,
    fat: 20,
    carbohydrates: 40,
    calories: 30,
    price: 90,
    images: {
      image: "https://code.s3.yandex.net/react/code/sauce-02.png",
      image_mobile: "https://code.s3.yandex.net/react/code/sauce-02-mobile.png",
      video: "https://www.youtube.com/embed/4qlCC1GOwFw?si=2KVdcoAJeE9g0q8t",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
      gif: "https://gifki.su/Uploads/Media/Feb20/Wed19/517/5076d85d.gif",
    },
    __v: 0,
  },
  {
    _id: "myaso-bessmertnyh-mollyuskov-protostomia",
    name: "Мясо бессмертных моллюсков Protostomia",
    type: "main",
    proteins: 433,
    fat: 244,
    carbohydrates: 33,
    calories: 420,
    price: 1337,
    images: {
      image: "https://code.s3.yandex.net/react/code/meat-02.png",
      image_mobile: "https://code.s3.yandex.net/react/code/meat-02-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/meat-02-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "sous-tradicionnyy-galakticheskiy",
    name: "Соус традиционный галактический",
    type: "sauce",
    proteins: 42,
    fat: 24,
    carbohydrates: 42,
    calories: 99,
    price: 15,
    images: {
      image: "https://code.s3.yandex.net/react/code/sauce-03.png",
      image_mobile: "https://code.s3.yandex.net/react/code/sauce-03-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/sauce-03-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "sous-firmennyy-space-sauce",
    name: "Соус фирменный Space Sauce",
    type: "sauce",
    proteins: 50,
    fat: 22,
    carbohydrates: 11,
    calories: 14,
    price: 80,
    images: {
      image: "https://code.s3.yandex.net/react/code/sauce-04.png",
      image_mobile: "https://code.s3.yandex.net/react/code/sauce-04-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/sauce-04-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "plody-falanskogo-dereva",
    name: "Плоды Фаланского дерева",
    type: "main",
    proteins: 20,
    fat: 5,
    carbohydrates: 55,
    calories: 77,
    price: 874,
    images: {
      image: "https://code.s3.yandex.net/react/code/sp_1.png",
      image_mobile: "https://code.s3.yandex.net/react/code/sp_1-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/sp_1-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "hrustyaschie-mineralnye-kolca",
    name: "Хрустящие минеральные кольца",
    type: "main",
    proteins: 808,
    fat: 689,
    carbohydrates: 609,
    calories: 986,
    price: 300,
    images: {
      image: "https://code.s3.yandex.net/react/code/mineral_rings.png",
      image_mobile:
        "https://code.s3.yandex.net/react/code/mineral_rings-mobile.png",
      image_large:
        "https://code.s3.yandex.net/react/code/mineral_rings-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "sous-s-shipami-antarianskogo-ploskohodca",
    name: "Соус с шипами Антарианского плоскоходца",
    type: "sauce",
    proteins: 101,
    fat: 99,
    carbohydrates: 100,
    calories: 100,
    price: 88,
    images: {
      image: "https://code.s3.yandex.net/react/code/sauce-01.png",
      image_mobile: "https://code.s3.yandex.net/react/code/sauce-01-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/sauce-01-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "kristally-marsianskih-alfa-saharidov",
    name: "Кристаллы марсианских альфа-сахаридов",
    type: "main",
    proteins: 234,
    fat: 432,
    carbohydrates: 111,
    calories: 189,
    price: 762,
    images: {
      image: "https://code.s3.yandex.net/react/code/core.png",
      image_mobile: "https://code.s3.yandex.net/react/code/core-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/core-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "mini-salat-ekzo-plantago",
    name: "Мини-салат Экзо-Плантаго",
    type: "main",
    proteins: 1,
    fat: 2,
    carbohydrates: 3,
    calories: 6,
    price: 4400,
    images: {
      image: "https://code.s3.yandex.net/react/code/salad.png",
      image_mobile: "https://code.s3.yandex.net/react/code/salad-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/salad-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },

  {
    _id: "syr-s-asteroidnoy-plesenyu",
    name: "Сыр с астероидной плесенью",
    type: "main",
    proteins: 84,
    fat: 48,
    carbohydrates: 420,
    calories: 3377,
    price: 4142,
    images: {
      image: "https://code.s3.yandex.net/react/code/cheese.png",
      image_mobile: "https://code.s3.yandex.net/react/code/cheese-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/cheese-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
  {
    _id: "flyuorescentnaya-bulka-r2-d3",
    name: "Флюоресцентная булка R2-D3",
    type: "bun",
    proteins: 44,
    fat: 26,
    carbohydrates: 85,
    calories: 643,
    price: 988,
    images: {
      image: "https://code.s3.yandex.net/react/code/bun-01.png",
      image_mobile: "https://code.s3.yandex.net/react/code/bun-01-mobile.png",
      image_large: "https://code.s3.yandex.net/react/code/bun-01-large.png",
      pdf: "https://pdftron.s3.amazonaws.com/downloads/pl/demo-annotated.pdf",
    },
    __v: 0,
  },
];
